"""Structural healthcare schema requirements.

Only schema facts that are genuinely required by the supported MIMIC-style
tables live here. Learned empirical constraints are generated by rule_engine.
"""

from __future__ import annotations

MIMIC_REQUIRED_FIELDS = {
    "hosp_patients": ("subject_id",),
    "icu_caregiver": ("caregiver_id",),
    "icu_d_items": ("itemid",),
    "hosp_d_labitems": ("itemid",),
    "hosp_admissions": ("subject_id", "hadm_id", "admittime", "dischtime"),
    "hosp_transfers": ("subject_id", "transfer_id"),
    "hosp_labevents": ("labevent_id", "subject_id", "itemid"),
    "hosp_microbiologyevents": ("microevent_id", "subject_id"),
    "icu_icustays": ("subject_id", "hadm_id", "stay_id", "intime", "outtime"),
    "icu_chartevents": ("subject_id", "stay_id", "itemid", "charttime"),
    "icu_inputevents": ("subject_id", "stay_id", "itemid", "starttime", "endtime"),
    "icu_outputevents": ("subject_id", "stay_id", "itemid", "charttime"),
    "icu_procedureevents": ("subject_id", "stay_id", "itemid", "starttime", "endtime"),
}
