"""
Base detector for Module 2 (Data Quality Detection).

All quality detectors should inherit from this class.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from time import perf_counter
from typing import Any

from models.detector_result import DetectorResult


class BaseDetector(ABC):
    """
    Base class for all quality detectors.

    Each detector receives:
        - dataset
        - dataset profile (generated by Module 1)

    Each detector returns:
        DetectorResult
    """

    def __init__(self, name: str):
        self.name = name

    def run(self, dataset: Any, profile: Any) -> DetectorResult:
        """
        Execute the detector while measuring execution time.
        """

        start = perf_counter()

        try:
            result = self.detect(dataset, profile)

            result.detector_name = self.name
            result.execution_time = perf_counter() - start
            result.success = True

            return result

        except Exception as exc:

            result = DetectorResult(
                detector_name=self.name,
                success=False,
                error=str(exc),
            )

            result.execution_time = perf_counter() - start

            return result

    @abstractmethod
    def detect(self, dataset: Any, profile: Any) -> DetectorResult:
        """
        Implement detector logic.

        Parameters
        ----------
        dataset
            Loaded dataset.

        profile
            DatasetProfile generated by Module 1.

        Returns
        -------
        DetectorResult
        """
        raise NotImplementedError